### ISSUE TITLE
Crashes when the user starts CalendarActivity when the device isn't online

### ISSUE THREAD

**Issue by lhwdev2008** [AppDevelopers2021/androidStudia#14]
-CalendarActivity.java:285

Fatal Exception: com.google.firebase.database.DatabaseException: Calls to setPersistenceEnabled() must be made before any other usage of FirebaseDatabase instance.
       at com.google.firebase.database.FirebaseDatabase.assertUnfrozen(FirebaseDatabase.java:332)
       at com.google.firebase.database.FirebaseDatabase.setPersistenceEnabled(FirebaseDatabase.java:285)
       at app.web.studia_kr.CalendarActivity.CalendarLoad(CalendarActivity.java:285)
       at app.web.studia_kr.CalendarActivity$3.onClick(CalendarActivity.java:179)
       at android.view.View.performClick(View.java:7862)
       at android.view.View.performClickInternal(View.java:7831)
       at android.view.View.access$3600(View.java:879)
       at android.view.View$PerformClick.run(View.java:29359)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by lee-jongwoo** [comment]
`setPersistence`를 mainActivity 맨 처음으로 옮겨주세요. 그리고 사용자 설정에서 오프라인 기능을 끄고 켤 수 있었으면 좋겠습니다.

**Comment by lhwdev2008** [comment]
> `setPersistence`를 mainActivity 맨 처음으로 옮겨주세요. 그리고 사용자 설정에서 오프라인 기능을 끄고 켤 수 있었으면 좋겠습니다.

네^^ 이미 바꿨는데 아직 푸시 안 했어요. 할거에용.
