### ISSUE TITLE
LoginActivity - Google Login Crashes

### ISSUE THREAD

**Issue by lee-jongwoo** [AppDevelopers2021/androidStudia#6]
```
2021-12-14 17:38:07.547 2917-2996/com.google.android.gms E/cvtc: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at cvtb.<init>(:com.google.android.gms@212423053@21.24.23 (190400-396046673):3)
        at cvtc.<init>(:com.google.android.gms@212423053@21.24.23 (190400-396046673):2)
        at cvlm.a(:com.google.android.gms@212423053@21.24.23 (190400-396046673):22)
        at tve.c(:com.google.android.gms@212423053@21.24.23 (190400-396046673):23)
        at tve.d(:com.google.android.gms@212423053@21.24.23 (190400-396046673):1)
        at axoy.call(:com.google.android.gms@212423053@21.24.23 (190400-396046673):32)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at ubg.c(:com.google.android.gms@212423053@21.24.23 (190400-396046673):6)
        at ubg.run(:com.google.android.gms@212423053@21.24.23 (190400-396046673):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at uhc.run(:com.google.android.gms@212423053@21.24.23 (190400-396046673):0)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by lhwdev2008** [comment]
**위의 에러는 Google Login Crash와 직접적인 관련이 있는 것처럼 보이지 않는다**.
우선, **startActivityForResult()를 바꿔서 코드가 자연스럽게 흘러가도록** 고쳤다.
현재는 **Android Project의 Fingerprint 관련해서 오류**가 생기는 듯 하다.

**Comment by lhwdev2008** [comment]
Fixed on December 26th, 2021.
